server:
  port: 8088

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/accounts/**

        - id: transaction-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/transactions/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG