spring:
  application:
    name: account-service

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: h2
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true #to load data post app start
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /api/v1/accounts
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024
  port: 8085

springdoc:
  api-docs:
    path: /docs
  show-actuator: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
